### PR TITLE
removed gstreamer dependency and added volume control

### PR DESCRIPTION
**Pull request by TheSpeedX**
GStreamer dependency remove
using ffpyplayer package
#1

### CODE REVIEW

**Comment by SubhrajitPrusty** [comment]
- Where did you test this? It just segfaults on my system
- There is another implementation of the player in `tools/tui.py` you'll have to add to that too
- Are there any hidden dependencies? (like ffmpeg)

**Comment by TheSpeedX** [comment]
<ul type="disc"> 
<li>Well it has been fixed and works now and added Volume Controls too.

</li>
<li>I have now added to tui.py</li>
<li>No dependencies except ffpyplayer, which is ffplay fully in cython. So we need not to install ffplay externally instead just install from pypi . I added it in setup.py dependencies. </li></ul>

**Comment by SubhrajitPrusty** [comment]
Can you explain what you changed in create_player and why do we need this?

**Comment by SubhrajitPrusty** [comment]
Also, if we're adding volume controls, the user should have the information about how much the volume is set at.

**Comment by TheSpeedX** [comment]
This is given as any function call to player object except get_frame() before its initialized will give 'Segmentation Fault'.
	Giving Audio URL to player will result in 'None' frame always as ffpyplayer returns video frame
	So one way around is to get video url and wait till frame is not None
	But Will Increase a bit of data usage.

I added Volume display too

**Pull request merged**
